// Copyright (C) 2019  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 19.1 (Build Build 670 09/22/2019)
// Created on Thu Oct 24 09:31:08 2019

VGA_SYNC VGA_SYNC_inst
(
	.clock_50Mhz(clock_50Mhz_sig) ,	// input  clock_50Mhz_sig
	.red(red_sig) ,	// input  red_sig
	.green(green_sig) ,	// input  green_sig
	.blue(blue_sig) ,	// input  blue_sig
	.red_out(red_out_sig) ,	// output  red_out_sig
	.green_out(green_out_sig) ,	// output  green_out_sig
	.blue_out(blue_out_sig) ,	// output  blue_out_sig
	.horiz_sync_out(horiz_sync_out_sig) ,	// output  horiz_sync_out_sig
	.vert_sync_out(vert_sync_out_sig) ,	// output  vert_sync_out_sig
	.video_on(video_on_sig) ,	// output  video_on_sig
	.pixel_clock(pixel_clock_sig) ,	// output  pixel_clock_sig
	.pixel_row(pixel_row_sig) ,	// output [9:0] pixel_row_sig
	.pixel_column(pixel_column_sig) 	// output [9:0] pixel_column_sig
);

